// <auto-generated />
using Dotnet_Mvc.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotnetMvc.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230626101401_addAllToDbSeedTable")]
    partial class addAllToDbSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNet_Mvc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Foot Wear"
                        });
                });

            modelBuilder.Entity("DotNet_Mvc.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Samsung S22 Ultra 108mp camera",
                            ImageURl = "",
                            Name = "Samsung S22 Ultra",
                            Price = 1000
                        });
                });

            modelBuilder.Entity("DotNet_Mvc.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "ashoknbasnetofficial@gmail.com",
                            FullName = "Ashok Basnet",
                            JobTitle = "Jonior Developer",
                            PhoneNumber = "9863614474"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "ashoknbasnetofficial@gmail.com",
                            FullName = "Rajan Rijal",
                            JobTitle = "Jonior Developer",
                            PhoneNumber = "9863614474"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "ashoknbasnetofficial@gmail.com",
                            FullName = "Anu Thapa",
                            JobTitle = "Techhincal Advistor",
                            PhoneNumber = "9863614474"
                        },
                        new
                        {
                            Id = 4,
                            EmailAddress = "rashikabhattarai59@gmail.com",
                            FullName = "Rashika Bhattarai",
                            JobTitle = "Student",
                            PhoneNumber = "9863614474"
                        },
                        new
                        {
                            Id = 5,
                            EmailAddress = "basnetpurna560@gmail.com",
                            FullName = "Purna Bahadur Basnet",
                            JobTitle = "Branch Manager",
                            PhoneNumber = "9844666715"
                        });
                });

            modelBuilder.Entity("DotNet_Mvc.Models.Products", b =>
                {
                    b.HasOne("DotNet_Mvc.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
